import { Fragment, useEffect, useState } from "react";
import { createFileRoute, Link, Navigate, useNavigate, useParams } from "@tanstack/react-router";
import { X } from "lucide-react";
import { api, Artifact, ArtifactList, AuditLogList, humanSize, Me, Receiver, RepoConfig, RepoPermission, RepoToken, repoEndpoint, Repository } from "@/api";
import { useAuth } from "@/authContext";
import { UpstreamStatus } from "@/components/feedback/upstream-status";
import { ConfirmModal } from "@/components/overlays/confirm-modal";
import { Alert } from "@/components/app-ui/alert";
import { Badge } from "@/components/app-ui/badge";
import { PageHeader } from "@/components/app-ui/page";
import { Card, CardContent } from "@/components/ui/card";
import { Select } from "@/components/app-ui/select";
import { StateBadge } from "@/components/app-ui/status-badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  TableWrap,
} from "@/components/app-ui/table";
import { MemberList } from "../new";
import { ApprovalList, SeverityBar, VersionDenies } from "../../approvals/index";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";
import { useTranslation } from "@/lib/i18n";

export const Route = createFileRoute("/workspace/repositories/$id/")({
  component: RepositoryDetailRoute,
});

function RepositoryDetailRoute() {
  const { me } = useAuth();
  return <RepositoryDetail me={me} />;
}

export function RepositoryDetail({ me }: { me: Me }) {
  const { t } = useTranslation();
  const { id, tab: routeTab } = useParams({ strict: false }) as { id?: string; tab?: string };
  const tab = routeTab ?? "artifacts";
  const [repo, setRepo] = useState<Repository | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    api.getRepository(Number(id)).then(setRepo).catch((e) => setError(e.message));
  }, [id]);

  if (!repo) return error ? <Alert>{error}</Alert> : <div className="text-sm text-muted-foreground">{t("common.loading")}</div>;

  // Tabs follow Nexus-style privileges: every authenticated reader can browse
  // Artifacts; Approvals needs the approve action; Permissions, Audit, Security
  // and Settings are for admins and auditors (auditors see them read-only).
  // Direct URL access to a hidden tab redirects to Artifacts.
  const gated = repo.type === "proxy" && Boolean(repo.config.approval?.enabled);
  const canApprove = me.admin || me.approver;
  const canAdminView = me.admin || me.auditor;
  const tabs = [
    { key: "artifacts", label: t("common.artifacts") },
    ...(repo.type === "proxy" && canApprove ? [{ key: "approvals", label: t("approval.title") }] : []),
    ...(canAdminView ? [{ key: "permissions", label: t("common.permissions") }, { key: "audit", label: "Audit" }, { key: "security", label: t("common.security") }, { key: "settings", label: "Settings" }] : []),
  ];

  if (!tabs.some((t) => t.key === tab)) {
    return <Navigate to="/workspace/repositories/$id/$tab" params={{ id: String(id), tab: "artifacts" }} replace />;
  }

  const endpoint = repoEndpoint(repo.format, repo.name);

  return (
    <>
      <PageHeader
        title={
          <div className="flex min-w-0 flex-wrap items-center gap-2">
            <span className="min-w-0 truncate">{repo.name}</span>
            <Badge variant="secondary">{repo.type}</Badge>
            <Badge>{repo.format}</Badge>
          </div>
        }
      />

      <Card size="sm" className="mb-4">
        <CardContent>
        <h2 className="m-0 mb-4 text-base font-semibold">{t("repo.client-endpoint")} <span className="text-xs font-normal text-muted-foreground">{t("repo.readonly-subtitle")}</span></h2>
        <div className="flex min-w-0 items-stretch gap-2 max-sm:flex-wrap max-sm:flex-col">
          <code className="flex-1 cursor-text select-all overflow-x-auto whitespace-nowrap rounded-[var(--radius)] border border-dashed border-border bg-input px-2.5 py-2 font-mono text-[13px] text-muted-foreground" title="Generated by forklift (read-only)">{endpoint.url}</code>
          <Button variant="outline" type="button"
            onClick={() => navigator.clipboard?.writeText(endpoint.url)}>{t("common.copy")}</Button>
        </div>
        {endpoint.hint && <p className="mt-2 text-sm text-muted-foreground">Configure in: {endpoint.hint}</p>}
        </CardContent>
      </Card>

      <nav className="mb-[18px] flex gap-1 border-b border-border max-[760px]:overflow-x-auto max-[760px]:pb-px">
        {tabs.map((t) => (
          <Link key={t.key} className={cn("mb-[-1px] rounded-t-[var(--radius)] border border-transparent border-b-0 px-3.5 py-[9px] text-sm text-muted-foreground hover:bg-muted hover:text-foreground hover:no-underline max-[760px]:whitespace-nowrap", tab === t.key && "border-border border-b-card bg-card text-primary")}
            to="/workspace/repositories/$id/$tab" params={{ id: String(id), tab: t.key }}>{t.label}</Link>
        ))}
      </nav>

      {tab === "artifacts" && <Artifacts repoId={repo.id} canDelete={!!me.admin} />}
      {tab === "permissions" && <RepoPermissions repoId={repo.id} />}
      {tab === "audit" && <AuditLogs repoId={repo.id} />}
      {tab === "approvals" && repo.type === "proxy" && (
        <>
          {gated && <ApprovalList repo={repo.name} showRepo={false} repoNames={[repo.name]} />}
          <VersionDenies repo={repo.name} showRepo={false} repoNames={[repo.name]} />
        </>
      )}
      {tab === "security" && <Security repo={repo} setRepo={setRepo} canWrite={!!me.admin} />}
      {tab === "settings" && <Settings repo={repo} setRepo={setRepo} canWrite={!!me.admin} />}
    </>
  );
}

// --- Source-IP ACL helpers: resolve an allow-list entry (a single IP or a CIDR
// block) to its first/last address and how many addresses it spans, so the UI
// can show the range and count a CIDR expands to. IPv4 and pure-hextet IPv6 are
// supported; embedded-IPv4 IPv6 (::ffff:1.2.3.4) is treated as unrecognised. ---

function ipv4ToInt(ip: string): number | null {
  const parts = ip.split(".");
  if (parts.length !== 4) return null;
  let n = 0;
  for (const p of parts) {
    if (!/^\d{1,3}$/.test(p)) return null;
    const v = Number(p);
    if (v > 255) return null;
    n = n * 256 + v;
  }
  return n >>> 0;
}
function intToIpv4(n: number): string {
  return [(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, n & 255].join(".");
}
function ipv6ToBig(ip: string): bigint | null {
  if (ip.includes(".")) return null;
  const halves = ip.split("::");
  if (halves.length > 2) return null;
  let groups: string[];
  if (halves.length === 2) {
    const head = halves[0] ? halves[0].split(":") : [];
    const tail = halves[1] ? halves[1].split(":") : [];
    const fill = 8 - head.length - tail.length;
    if (fill < 1) return null;
    groups = [...head, ...Array(fill).fill("0"), ...tail];
  } else {
    groups = ip.split(":");
  }
  if (groups.length !== 8) return null;
  let n = 0n;
  for (const g of groups) {
    if (!/^[0-9a-fA-F]{1,4}$/.test(g)) return null;
    n = (n << 16n) + BigInt(parseInt(g, 16));
  }
  return n;
}
function bigToIpv6(n: bigint): string {
  const g: string[] = [];
  for (let i = 7; i >= 0; i--) g.push(((n >> BigInt(i * 16)) & 0xffffn).toString(16));
  // Compress the longest run (>= 2) of zero groups to "::".
  let bestStart = -1, bestLen = 0, curStart = -1, curLen = 0;
  for (let i = 0; i < 8; i++) {
    if (g[i] === "0") {
      if (curStart < 0) { curStart = i; curLen = 0; }
      if (++curLen > bestLen) { bestLen = curLen; bestStart = curStart; }
    } else { curStart = -1; curLen = 0; }
  }
  if (bestLen < 2) return g.join(":");
  return `${g.slice(0, bestStart).join(":")}::${g.slice(bestStart + bestLen).join(":")}`;
}

type AclInfo =
  | { kind: "invalid" }
  | { kind: "single" }
  | { kind: "range"; first: string; last: string; count: bigint; exp: number };

// aclEntryInfo classifies one allow-list line.
function aclEntryInfo(entry: string): AclInfo {
  const slash = entry.indexOf("/");
  if (slash < 0) {
    return ipv4ToInt(entry) !== null || ipv6ToBig(entry) !== null ? { kind: "single" } : { kind: "invalid" };
  }
  const addr = entry.slice(0, slash);
  const prefStr = entry.slice(slash + 1);
  if (!/^\d{1,3}$/.test(prefStr)) return { kind: "invalid" };
  const prefix = Number(prefStr);

  const v4 = ipv4ToInt(addr);
  if (v4 !== null) {
    if (prefix > 32) return { kind: "invalid" };
    const exp = 32 - prefix;
    const mask = prefix === 0 ? 0 : (0xffffffff << exp) >>> 0;
    const first = (v4 & mask) >>> 0;
    const count = 1n << BigInt(exp);
    const last = (first + Number(count) - 1) >>> 0;
    return { kind: "range", first: intToIpv4(first), last: intToIpv4(last), count, exp };
  }
  const v6 = ipv6ToBig(addr);
  if (v6 !== null) {
    if (prefix > 128) return { kind: "invalid" };
    const exp = 128 - prefix;
    const count = 1n << BigInt(exp);
    const first = prefix === 0 ? 0n : (v6 >> BigInt(exp)) << BigInt(exp);
    return { kind: "range", first: bigToIpv6(first), last: bigToIpv6(first + count - 1n), count, exp };
  }
  return { kind: "invalid" };
}

const ACL_MAX_SAFE = 9_007_199_254_740_991n;
// fmtCount renders an address count, falling back to power-of-two form when it
// exceeds the safe-integer range (large IPv6 blocks).
function fmtCount(count: bigint, exp: number): string {
  const noun = count === 1n ? "address" : "addresses";
  return count <= ACL_MAX_SAFE ? `${Number(count).toLocaleString()} ${noun}` : `2^${exp} addresses`;
}

// LinesInput is a textarea for "one value per line" lists. It keeps the raw text
// in local state so a blank line — e.g. the one created by pressing Enter — is
// not swallowed mid-edit, and reports the trimmed, non-empty lines to onChange.
function LinesInput({ value, onChange, rows = 3, placeholder }: {
  value: string[];
  onChange: (lines: string[]) => void;
  rows?: number;
  placeholder?: string;
}) {
  const joined = value.join("\n");
  const [text, setText] = useState(joined);
  // Re-sync only when the external value diverges from what the current text
  // parses to (e.g. the repository changed), never on plain keystrokes.
  useEffect(() => {
    if (text.split("\n").map((s) => s.trim()).filter(Boolean).join("\n") !== joined) setText(joined);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [joined]);
  return (
    <Textarea rows={rows} placeholder={placeholder} value={text}
      onChange={(e) => {
        setText(e.target.value);
        onChange(e.target.value.split("\n").map((s) => s.trim()).filter(Boolean));
      }} />
  );
}

// PolicyFlow draws every gate left to right in the order a proxy request is
// evaluated, so an admin sees the whole pipeline at a glance. The order mirrors
// the serving path: the source-IP allow list runs first, then package approval
// and the vulnerability and license gates, then age and stored-blob artifact
// scanning. All gates are always shown; a disabled one is dimmed in place. An
// enabled node's colour encodes whether it can refuse the request
// (block/enforce) or merely logs (warn/audit). Every gate is configured by a
// panel on this same tab.
function PolicyFlow({ config }: { config: RepoConfig }) {
  const { t } = useTranslation();
  const ipacl = config.ip_acl;
  const approval = config.approval;
  const vuln = config.vuln;
  const license = config.license;
  const artifactScan = config.artifact_scan;
  const age = config.age_policy;

  type Sev = "block" | "warn" | "audit";
  const sev = (action?: string): Sev =>
    action === "block" ? "block" : action === "warn" ? "warn" : "audit";

  type Node = { name: string; label: string; enabled: boolean; severity: Sev; action: string };
  const nodes: Node[] = [
    {
      name: "Source IP ACL",
      label: t("repo.source-ip-acl"),
      enabled: !!ipacl?.enabled,
      severity: "block",
      action: `allow-list · ${(ipacl?.allow ?? []).length}`,
    },
    {
      name: "Package approval",
      label: t("repo.package-approval"),
      enabled: !!approval?.enabled,
      severity: (approval?.mode || "enforce") === "enforce" ? "block" : "audit",
      action: (approval?.mode || "enforce") === "enforce" ? "enforce" : "audit",
    },
    {
      name: "Vulnerability",
      label: "Vulnerability",
      enabled: !!vuln?.enabled,
      severity: sev(vuln?.action),
      action: `${vuln?.action || "audit"} · ≥${vuln?.threshold || "high"}`,
    },
    {
      name: "License",
      label: t("common.license"),
      enabled: !!license?.enabled,
      severity: sev(license?.action),
      action: license?.action || "audit",
    },
    {
      name: "Age",
      label: "Age",
      enabled: !!age?.enabled,
      severity: age?.action === "warn" ? "warn" : "block",
      action: `${age?.action || "block"}${age?.min_age && age.min_age !== "0s" ? ` · <${age.min_age}` : ""}`,
    },
    {
      name: "Artifact scan",
      label: "Artifact scan",
      enabled: !!artifactScan?.enabled,
      severity: sev(artifactScan?.action),
      action: `${artifactScan?.action || "audit"} · ≥${artifactScan?.threshold || "high"}`,
    },
  ];

  const arrow = (
    <span className="inline-flex w-[30px] flex-none items-center self-center" aria-hidden="true">
      <span className="h-0.5 flex-1 rounded-sm bg-[linear-gradient(90deg,var(--muted)_0_55%,transparent_55%_100%)] bg-[length:8px_2px] bg-repeat-x [animation:pf-flow_0.6s_linear_infinite] motion-reduce:animate-none" />
      <span className="h-0 w-0 flex-none border-y-4 border-l-[5px] border-y-transparent border-l-muted-foreground" />
    </span>
  );

  return (
    <Card size="sm" className="mb-4">
      <CardContent>
        <h2 className="m-0 mb-1 text-base font-semibold">
          {t("repo.policy-order")} <span className="text-xs font-normal text-muted-foreground">{t("repo.policy-order-subtitle")}</span>
        </h2>
        <p className="mt-0 mb-4 text-sm text-muted-foreground">
          {t("repo.policy-order-desc")} <span className="text-destructive">{t("common.policy.block")}</span>/enforce
          gate can refuse the request; <span className="text-primary">{t("common.policy.warn")}</span> {t("repo.policy-order-desc-2")}
        </p>
        <div className="flex items-stretch gap-2 overflow-x-auto pb-1">
          <span className="self-center whitespace-nowrap text-[11px] tracking-[0.05em] text-muted-foreground uppercase">{t("common.request")}</span>
          {nodes.map((n, i) => (
            <Fragment key={n.name}>
              {arrow}
              <div
                className={cn(
                  "flex flex-none flex-col gap-0.5 rounded-[var(--radius)] border border-border bg-input px-3 py-2",
                  n.enabled && n.severity === "block" && "border-destructive",
                  n.enabled && n.severity === "warn" && "border-primary",
                  !n.enabled && "border-dashed opacity-45",
                )}
              >
                <span className="mb-0.5 inline-flex h-[22px] min-w-[22px] items-center justify-center self-start rounded-full border border-border bg-card px-[5px] text-sm font-bold text-foreground tabular-nums">{i + 1}</span>
                <span className="whitespace-nowrap text-[13px] font-semibold">{n.label}</span>
                <span
                  className={cn(
                    "whitespace-nowrap text-[11px] text-muted-foreground",
                    n.enabled && n.severity === "block" && "text-destructive",
                    n.enabled && n.severity === "warn" && "text-primary",
                  )}
                >
                  {n.enabled ? n.action : "off"}
                </span>
              </div>
            </Fragment>
          ))}
          {arrow}
          <span className="self-center whitespace-nowrap text-[11px] tracking-[0.05em] text-muted-foreground uppercase">{t("repo.served")}</span>
        </div>
      </CardContent>
    </Card>
  );
}

function Settings({ repo, setRepo, canWrite }: { repo: Repository; setRepo: (r: Repository) => void; canWrite: boolean }) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [confirmPurge, setConfirmPurge] = useState(false);
  const [purged, setPurged] = useState<number | null>(null);

  const purge = async () => {
    setError("");
    setPurged(null);
    try {
      const { deleted } = await api.purgeArtifacts(repo.id);
      setConfirmPurge(false);
      setPurged(deleted);
    } catch (e) {
      setError((e as Error).message);
      setConfirmPurge(false);
    }
  };

  const save = async () => {
    setError("");
    setSaved(false);
    try {
      await api.updateRepository(repo.id, { upstream_url: repo.upstream_url, config: repo.config });
      setSaved(true);
    } catch (e) {
      setError((e as Error).message);
    }
  };

  const del = async () => {
    await api.deleteRepository(repo.id);
    navigate({ to: "/workspace/repositories" });
  };

  const cache = repo.config.cache;

  return (
    <>
      {!canWrite && (
        <p className="mt-0 text-sm text-muted-foreground">
          {t("repo.readonly-note")}
        </p>
      )}
      <ConfirmModal
        open={confirmDelete}
        title={`Delete repository "${repo.name}"?`}
        message={t("repo.delete-confirm")}
        confirmLabel={t("common.delete")}
        danger
        onConfirm={del}
        onCancel={() => setConfirmDelete(false)}
      />

      {/* For an auditor (canWrite=false) the whole settings form is disabled via
          fieldset[disabled], which blocks every control (mouse and keyboard);
          they can read the configuration but not change it. */}
      <fieldset className="m-0 min-w-0 border-0 p-0 disabled:opacity-65" disabled={!canWrite}>
      <Card size="sm" className="mb-4">
        <CardContent>
        <h2 className="m-0 mb-3 text-base font-semibold">{t("common.state")}</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          {repo.disabled
            ? t("repo.offline-note")
            : t("repo.online-note")}
        </p>
        {canWrite ? (
          <label className="inline-flex items-center gap-2 text-sm">
            <Switch
              checked={!repo.disabled}
              onCheckedChange={(online) => {
                setError("");
                api.setRepositoryDisabled(repo.id, !online).then(setRepo).catch((e) => setError((e as Error).message));
              }}
              aria-label={repo.disabled ? t("repo.offline") : t("repo.online")}
            />
            <span>{repo.disabled ? t("repo.offline") : t("repo.online")}</span>
          </label>
        ) : (
          <StateBadge state={repo.disabled ? "offline" : "online"}>{repo.disabled ? t("repo.offline") : t("repo.online")}</StateBadge>
        )}
        </CardContent>
      </Card>

      {(repo.type === "proxy" || repo.type === "group") && (
        <h2 className="mt-6 mb-3 border-b border-border pb-[7px] text-xs font-semibold text-muted-foreground uppercase tracking-normal">{t("common.repository")}</h2>
      )}

      {repo.type === "proxy" && (
        <Card size="sm" className="mb-4">
          <CardContent>
          <div className="mb-4 flex items-start justify-between gap-3 max-sm:flex-col max-sm:items-stretch">
            <h2 className="m-0 text-base font-semibold">{t("common.upstream")}</h2>
            <UpstreamStatus repoId={repo.id} withButton />
          </div>
          <Input value={repo.upstream_url}
            onChange={(e) => setRepo({ ...repo, upstream_url: e.target.value })} />
          </CardContent>
        </Card>
      )}

      {repo.type === "group" && <GroupMembers repo={repo} setRepo={setRepo} />}

      {repo.type === "proxy" && (
        <Card size="sm" className="mb-4">
          <CardContent>
          <h2 className="m-0 mb-4 text-base font-semibold">{t("common.cache")}</h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={cache.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, enabled: !!checked } } })} />
            <span>{t("repo.enable-caching")}</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-3">
            <Field><FieldLabel>{t("repo.metadata-ttl")}</FieldLabel>
              <Input value={cache.metadata_ttl}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, metadata_ttl: e.target.value } } })} /></Field>
            <Field><FieldLabel>{t("repo.negative-ttl")}</FieldLabel>
              <Input value={cache.negative_ttl}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, negative_ttl: e.target.value } } })} /></Field>
            <Field><FieldLabel>{t("repo.max-size")}</FieldLabel>
              <Input type="number" value={cache.max_size_bytes}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, max_size_bytes: Number(e.target.value) } } })} /></Field>
          </FieldGroup>
          </CardContent>
        </Card>
      )}

      {repo.type !== "group" && (
        <Card size="sm" className="mb-4">
          <CardContent>
          <h2 className="m-0 mb-4 text-base font-semibold">{t("repo.artifact-retention")} <span className="text-xs font-normal text-muted-foreground">{t("repo.retention-subtitle")}</span></h2>
          <Field>
            <FieldLabel>{t("repo.idle-ttl")}</FieldLabel>
              <Input value={repo.config.retention?.idle_ttl ?? ""}
                placeholder="0"
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, retention: { idle_ttl: e.target.value } } })} />
          </Field>
          <p className="mb-0 mt-4 text-sm text-muted-foreground">Artifacts not served for this long are deleted automatically; each removal is recorded in the audit log. Based on last-served time.</p>
          </CardContent>
        </Card>
      )}

      </fieldset>

      {error && <Alert className="mb-4">{error}</Alert>}
      {saved && <div className="mb-4 text-sm text-muted-foreground">{t("common.saved")}</div>}
      {canWrite && <Button onClick={save}>{t("common.save-changes")}</Button>}

      {canWrite && (
      <>
      <ConfirmModal
        open={confirmPurge}
        title={`Purge all artifacts in "${repo.name}"?`}
        message={t("repo.purge-confirm")}
        confirmLabel={t("repo.purge")}
        danger
        onConfirm={purge}
        onCancel={() => setConfirmPurge(false)}
      />

      <Card size="sm" className="mb-4 mt-4 border-destructive/70">
        <CardContent>
        <h2 className="m-0 mb-3 text-base font-semibold text-destructive">{t("common.danger-zone")}</h2>
        {repo.type !== "group" && (
          <>
            <p className="text-sm leading-relaxed text-muted-foreground">{t("repo.purge-note")}</p>
            {purged !== null && <div className="mb-3 text-sm text-muted-foreground">Purged {purged} {purged === 1 ? "artifact" : "artifacts"}.</div>}
            <Button variant="destructive" onClick={() => setConfirmPurge(true)}>{t("repo.purge-all")}</Button>
            <div className="my-4 border-t border-border" />
          </>
        )}
        <p className="text-sm leading-relaxed text-muted-foreground">{t("repo.delete-note")}</p>
        <Button variant="destructive" onClick={() => setConfirmDelete(true)}>{t("repo.delete")}</Button>
        </CardContent>
      </Card>
      </>
      )}
    </>
  );
}

// Security collects everything that governs who may reach the repository and
// what is allowed to pass: the source-IP allow list (every repo type) and, for
// a proxy, the supply-chain gates (age, package approval, vulnerability and
// license policy), plus artifact-byte scan gating for stored blobs. Saving
// writes the whole repo config, same as Settings.
function Security({ repo, setRepo, canWrite }: { repo: Repository; setRepo: (r: Repository) => void; canWrite: boolean }) {
  const { t } = useTranslation();
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);

  // Receivers offered as approval-notification targets (managed under
  // Notifications). Loaded for proxy repos, where the approval gate runs.
  const [receivers, setReceivers] = useState<Receiver[]>([]);
  useEffect(() => {
    if (repo.type === "proxy") api.listReceivers().then(setReceivers).catch(() => setReceivers([]));
  }, [repo.type]);
  // Sample-alarm preview / send state for the approval notification panel.
  const [sampleBusy, setSampleBusy] = useState<"" | "preview" | "send">("");
  const [sampleErr, setSampleErr] = useState("");
  const [preview, setPreview] = useState<{ payload: Record<string, string>; receivers: { name: string; exists: boolean; enabled: boolean }[] } | null>(null);
  const [sampleResults, setSampleResults] = useState<{ name: string; ok: boolean; error?: string }[] | null>(null);

  const doPreview = async () => {
    setSampleErr(""); setSampleResults(null); setSampleBusy("preview");
    try { setPreview(await api.previewRepoSample(repo.id)); }
    catch (e) { setSampleErr((e as Error).message); }
    finally { setSampleBusy(""); }
  };
  const doSendSample = async () => {
    setSampleErr(""); setPreview(null); setSampleBusy("send");
    try { setSampleResults((await api.sendRepoSample(repo.id)).results); }
    catch (e) { setSampleErr((e as Error).message); }
    finally { setSampleBusy(""); }
  };

  const save = async () => {
    setError("");
    setSaved(false);
    try {
      await api.updateRepository(repo.id, { upstream_url: repo.upstream_url, config: repo.config });
      setSaved(true);
    } catch (e) {
      setError((e as Error).message);
    }
  };

  const age = repo.config.age_policy;
  // Older repos may predate the approval config section.
  const approval = repo.config.approval ?? { enabled: false, mode: "enforce", auto_approve: [] };
  const vuln = repo.config.vuln ?? { enabled: false, action: "audit", threshold: "high", ignore: [] };
  const license = repo.config.license ?? { enabled: false, action: "audit", deny: [], allow: [] };
  const artifactScan = repo.config.artifact_scan ?? { enabled: false, scanner: "grype", action: "audit", threshold: "high" };
  // Source-IP ACL applies to every repository type (including group entry).
  const ipacl = repo.config.ip_acl ?? { enabled: false, allow: [] };
  // Approval-notification receivers selected for this repository.
  const selectedReceivers = repo.config.notify?.receivers ?? [];
  const setSelectedReceivers = (next: string[]) =>
    setRepo({ ...repo, config: { ...repo.config, notify: { ...repo.config.notify, receivers: next } } });

  // Resolve each allow entry to a range/count for the breakdown shown below the
  // textarea, and a running total (capped at the safe-integer range).
  const aclRows = (ipacl.allow ?? []).map((entry) => ({ entry, info: aclEntryInfo(entry) }));
  let aclTotal = 0n;
  for (const { info } of aclRows) {
    if (info.kind === "single") aclTotal += 1n;
    else if (info.kind === "range") aclTotal += info.count;
  }

  return (
    <>
      {!canWrite && (
        <p className="mt-0 text-sm text-muted-foreground">
          {t("repo.readonly-note")}
        </p>
      )}

      {/* For an auditor (canWrite=false) the whole form is disabled via
          fieldset[disabled], which blocks every control (mouse and keyboard);
          they can read the configuration but not change it. */}
      <fieldset className="m-0 min-w-0 border-0 p-0 disabled:opacity-65" disabled={!canWrite}>

      <h2 className="mt-0 mb-3 border-b border-border pb-[7px] text-xs font-semibold text-muted-foreground uppercase tracking-normal">{t("repo.access-control")}</h2>

      <Card size="sm" className="mb-4">
        <CardContent>
        <h2 className="m-0 mb-4 text-base font-semibold">{t("repo.source-ip-acl")} <span className="text-xs font-normal text-muted-foreground">{t("repo.acl-subtitle")}</span></h2>
        <label className="inline-flex items-center gap-2 text-sm">
          <Switch
            checked={ipacl.enabled}
            onCheckedChange={(v) => setRepo({ ...repo, config: { ...repo.config, ip_acl: { ...ipacl, enabled: v } } })}
            aria-label={t("repo.restrict-by-ip")}
          />
          <span>{t("repo.restrict-by-ip")}</span>
        </label>
        <Field className="mt-4">
          <FieldLabel>{t("repo.allowed-ips")}</FieldLabel>
          <LinesInput rows={4} placeholder={"10.0.0.0/16\n203.0.113.5\n2001:db8::/32"}
            value={ipacl.allow ?? []}
            onChange={(allow) => setRepo({ ...repo, config: { ...repo.config, ip_acl: { ...ipacl, allow } } })} />
        </Field>
        {aclRows.length > 0 && (
          <div className="mt-2.5 flex flex-col gap-1">
            {aclRows.map(({ entry, info }, i) => (
              <div key={`${entry}-${i}`} className="flex flex-wrap items-baseline gap-2 text-xs">
                <code className="font-mono text-foreground">{entry}</code>
                {info.kind === "invalid" && <span className="text-destructive">{t("repo.invalid-cidr")}</span>}
                {info.kind === "single" && <span className="text-muted-foreground">{t("repo.single-host")}</span>}
                {info.kind === "range" && (
                  <span className="text-muted-foreground">{info.first} – {info.last} · {fmtCount(info.count, info.exp)}</span>
                )}
              </div>
            ))}
            <div className="mt-1 text-xs text-muted-foreground">
              Total allowed: {aclTotal <= ACL_MAX_SAFE
                ? `${Number(aclTotal).toLocaleString()} ${aclTotal === 1n ? "address" : "addresses"}`
                : "very large (includes a wide IPv6 range)"}
            </div>
          </div>
        )}
        <p className="mb-0 mt-4 text-sm leading-relaxed text-muted-foreground">
          When enabled, only requests from a matching source IP are served; others get 403. The client IP is
          the first X-Forwarded-For hop set by your ingress, falling back to the TCP peer address. An empty
          list blocks everything. For a group, this guards entry to the group; member repositories are not
          re-checked on group fan-out.
        </p>
        </CardContent>
      </Card>

      {repo.type === "proxy" && (
        <h2 className="mt-6 mb-3 border-b border-border pb-[7px] text-xs font-semibold text-muted-foreground uppercase tracking-normal">{t("repo.supply-chain")} <span className="font-normal normal-case">{t("repo.policies-subtitle")}</span></h2>
      )}

      {/* The evaluation-order flow only makes sense for the proxy serving path. */}
      {repo.type === "proxy" && <PolicyFlow config={repo.config} />}

      {repo.type === "proxy" && (
        <Card size="sm" className="mb-4">
          <CardContent>
          <h2 className="m-0 mb-4 text-base font-semibold">{t("repo.age-policy")}</h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={age.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, enabled: !!checked } } })} />
            <span>{t("repo.enable-cooldown")}</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-2">
            <Field><FieldLabel>{t("repo.min-age-placeholder")}</FieldLabel>
              <Input value={age.min_age}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, min_age: e.target.value } } })} /></Field>
            <Field><FieldLabel>{t("common.action")}</FieldLabel>
              <Select value={age.action}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, action: v } } })}
                options={[
                  { value: "block", label: t("common.policy.block") },
                  { value: "warn", label: t("common.policy.warn") },
                ]} /></Field>
          </FieldGroup>
          </CardContent>
        </Card>
      )}

      {repo.type === "proxy" && (
        <Card size="sm" className="mb-4">
          <CardContent>
          <h2 className="m-0 mb-4 text-base font-semibold">{t("repo.package-approval")} <span className="text-xs font-normal text-muted-foreground">{t("repo.quarantine-subtitle")}</span></h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={approval.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, approval: { ...approval, enabled: !!checked } } })} />
            <span>{t("repo.require-approval")}</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-2">
            <Field><FieldLabel>{t("common.mode")}</FieldLabel>
              <Select value={approval.mode || "enforce"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, approval: { ...approval, mode: v } } })}
                options={[
                  { value: "enforce", label: "enforce (block unapproved)" },
                  { value: "audit", label: "audit (serve, log only)" },
                ]} /></Field>
            <Field><FieldLabel>{t("repo.auto-approve-patterns")}</FieldLabel>
              <Textarea rows={3}
                value={(approval.auto_approve ?? []).join("\n")}
                placeholder={"@company/*"}
                onChange={(e) => setRepo({
                  ...repo,
                  config: {
                    ...repo.config,
                    approval: { ...approval, auto_approve: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
                  },
                })} /></Field>
          </FieldGroup>
          <p className="mt-4 text-sm text-muted-foreground">Approval admits whole packages; version freshness is still gated by the age policy.</p>

          <div className="mt-5 border-t border-border pt-4">
            <h3 className="m-0 mb-2 text-sm font-semibold">
              {t("notification.title")} <span className="text-xs font-normal text-muted-foreground">{t("repo.quarantine-desc")}</span>
            </h3>
            {selectedReceivers.length > 0 && (
              <div className="flex min-w-0 items-center gap-2 max-sm:flex-wrap mb-2 flex-wrap gap-1.5">
                {selectedReceivers.map((name) => (
                  <Badge key={name} className="gap-1">
                    {name}
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon-xs"
                      className="-mr-1 size-4 rounded-full text-muted-foreground hover:bg-background/40 hover:text-foreground"
                      title={`Remove ${name}`}
                      onClick={() => setSelectedReceivers(selectedReceivers.filter((n) => n !== name))}
                    >
                      <X className="size-3" aria-hidden="true" />
                      <span className="sr-only">Remove {name}</span>
                    </Button>
                  </Badge>
                ))}
              </div>
            )}
            <Select value=""
              placeholder={receivers.length === 0 ? "No receivers — add under Notifications" : "Add notification…"}
              onChange={(v) => v && setSelectedReceivers([...selectedReceivers, v])}
              options={receivers
                .filter((rcv) => !selectedReceivers.includes(rcv.name))
                .map((rcv) => ({ value: rcv.name, label: rcv.enabled ? rcv.name : `${rcv.name} (disabled)` }))} />
            <p className="mt-2 text-sm text-muted-foreground">{t("repo.receivers-note")}</p>
            <div className="flex min-w-0 items-center gap-2 max-sm:flex-wrap gap-2">
              <Button variant="outline" type="button" disabled={!!sampleBusy} onClick={doPreview}>
                {sampleBusy === "preview" ? t("common.loading") : "Preview"}
              </Button>
              <Button variant="outline" type="button" disabled={!!sampleBusy || selectedReceivers.length === 0} onClick={doSendSample}>
                {sampleBusy === "send" ? t("common.sending") : "Send sample alarm"}
              </Button>
            </div>
            {sampleErr && <Alert className="mt-2">{sampleErr}</Alert>}
            {preview && (
              <div className="mt-2.5 rounded-[var(--radius)] border border-border bg-input p-3">
                <div className="mb-1.5 text-xs text-muted-foreground">
                  Would send to: {preview.receivers.filter((x) => x.enabled).map((x) => x.name).join(", ") || "no enabled receiver selected"}
                </div>
                <div className="mb-2 text-sm">{preview.payload.text}</div>
                <pre className="m-0 overflow-x-auto text-xs">{JSON.stringify(preview.payload, null, 2)}</pre>
              </div>
            )}
            {sampleResults && (
              <div className="mt-2.5 space-y-0.5">
                {sampleResults.map((res, i) => (
                  <div key={i} className={cn("text-xs", res.ok ? "text-muted-foreground" : "text-destructive")}>
                    {res.ok ? `✓ sent to ${res.name}` : `✗ ${res.name}: ${res.error}`}
                  </div>
                ))}
              </div>
            )}
          </div>
          </CardContent>
        </Card>
      )}

      {repo.type === "proxy" && (
        <Card size="sm" className="mb-4">
          <CardContent>
          <h2 className="m-0 mb-4 text-base font-semibold">{t("repo.vuln-policy")} <span className="text-xs font-normal text-muted-foreground">{t("repo.vuln-subtitle")}</span></h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={vuln.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, enabled: !!checked } } })} />
            <span>{t("repo.vuln-gate")}</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-2">
            <Field><FieldLabel>{t("common.threshold")}</FieldLabel>
              <Select value={vuln.threshold || "high"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, threshold: v } } })}
                options={[
                  { value: "critical", label: "critical" },
                  { value: "high", label: "high" },
                  { value: "medium", label: "medium" },
                  { value: "low", label: "low" },
                ]} /></Field>
            <Field><FieldLabel>{t("common.action")}</FieldLabel>
              <Select value={vuln.action || "audit"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, action: v } } })}
                options={[
                  { value: "block", label: "block (refuse to serve)" },
                  { value: "warn", label: "warn (serve, log)" },
                  { value: "audit", label: "audit (serve, log)" },
                ]} /></Field>
          </FieldGroup>
          <Field className="mt-4">
          <FieldLabel>{t("repo.ignore-advisories")}</FieldLabel>
          <Textarea rows={3}
            value={(vuln.ignore ?? []).join("\n")}
            placeholder={"CVE-2026-1234"}
            onChange={(e) => setRepo({
              ...repo,
              config: {
                ...repo.config,
                vuln: { ...vuln, ignore: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
              },
            })} />
          </Field>
          <label className="mt-3 flex items-center gap-2 text-sm">
            <Checkbox checked={!!vuln.block_unscanned}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, block_unscanned: !!checked } } })} />
            <span>{t("repo.block-unscanned")}</span>
          </label>
          <p className="mb-0 mt-4 text-sm text-muted-foreground">Coordinate match against OSV (direct dependency only); transitive deps and artifact integrity are out of scope. Newly disclosed advisories surface on the next re-scan.</p>
          </CardContent>
        </Card>
      )}

      {repo.type === "proxy" && (
        <Card size="sm" className="mb-4">
          <CardContent>
          <h2 className="m-0 mb-4 text-base font-semibold">{t("repo.license-policy")} <span className="text-xs font-normal text-muted-foreground">{t("repo.license-subtitle")}</span></h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={license.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, license: { ...license, enabled: !!checked } } })} />
            <span>{t("repo.license-gate")}</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-2">
            <Field><FieldLabel>{t("common.action")}</FieldLabel>
              <Select value={license.action || "audit"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, license: { ...license, action: v } } })}
                options={[
                  { value: "block", label: "block (refuse to serve)" },
                  { value: "warn", label: "warn (serve, log)" },
                  { value: "audit", label: "audit (serve, log)" },
                ]} /></Field>
            <Field><FieldLabel>{t("repo.deny-licenses")}</FieldLabel>
              <Textarea rows={3}
                value={(license.deny ?? []).join("\n")}
                placeholder={"GPL-3.0\nAGPL-3.0"}
                onChange={(e) => setRepo({
                  ...repo,
                  config: {
                    ...repo.config,
                    license: { ...license, deny: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
                  },
                })} /></Field>
            <Field><FieldLabel>{t("repo.allow-licenses")}</FieldLabel>
              <Textarea rows={3}
                value={(license.allow ?? []).join("\n")}
                placeholder={"MIT\nApache-2.0\nBSD-3-Clause"}
                onChange={(e) => setRepo({
                  ...repo,
                  config: {
                    ...repo.config,
                    license: { ...license, allow: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
                  },
                })} /></Field>
          </FieldGroup>
          <label className="mt-3 flex items-center gap-2 text-sm">
            <Checkbox checked={!!license.block_unresolved}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, license: { ...license, block_unresolved: !!checked } } })} />
            <span>{t("repo.block-unresolved")}</span>
          </label>
          <p className="mb-0 mt-4 text-sm text-muted-foreground">{t("repo.license-note")}</p>
          </CardContent>
        </Card>
      )}

      {repo.type !== "group" && (
        <Card size="sm" className="mb-4">
          <CardContent>
          <h2 className="m-0 mb-4 text-base font-semibold">Artifact scan policy <span className="text-xs font-normal text-muted-foreground">stored blob gate</span></h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={artifactScan.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, artifact_scan: { ...artifactScan, enabled: !!checked } } })} />
            <span>Gate downloads by the latest isolated scanner result</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-2">
            <Field><FieldLabel>Scanner</FieldLabel>
              <Input value={artifactScan.scanner || "grype"}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, artifact_scan: { ...artifactScan, scanner: e.target.value.trim() || "grype" } } })} /></Field>
            <Field><FieldLabel>Config hash</FieldLabel>
              <Input value={artifactScan.config_hash || ""}
                placeholder="default"
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, artifact_scan: { ...artifactScan, config_hash: e.target.value.trim() } } })} /></Field>
            <Field><FieldLabel>{t("common.threshold")}</FieldLabel>
              <Select value={artifactScan.threshold || "high"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, artifact_scan: { ...artifactScan, threshold: v } } })}
                options={[
                  { value: "critical", label: "critical" },
                  { value: "high", label: "high" },
                  { value: "medium", label: "medium" },
                  { value: "low", label: "low" },
                ]} /></Field>
            <Field><FieldLabel>{t("common.action")}</FieldLabel>
              <Select value={artifactScan.action || "audit"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, artifact_scan: { ...artifactScan, action: v } } })}
                options={[
                  { value: "block", label: "block (refuse to serve)" },
                  { value: "warn", label: "warn (serve, log)" },
                  { value: "audit", label: "audit (serve, log)" },
                ]} /></Field>
          </FieldGroup>
          <label className="mt-3 flex items-center gap-2 text-sm">
            <Checkbox checked={!!artifactScan.block_unscanned}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, artifact_scan: { ...artifactScan, block_unscanned: !!checked } } })} />
            <span>Block artifacts with no completed scan result when action is block</span>
          </label>
          <p className="mb-0 mt-4 text-sm text-muted-foreground">
            The server only checks stored results here. Scanner execution stays in the isolated worker; changing scanner config should also change the config hash.
          </p>
          </CardContent>
        </Card>
      )}

      </fieldset>

      {error && <Alert className="mb-4">{error}</Alert>}
      {saved && <div className="mb-4 text-sm text-muted-foreground">{t("common.saved")}</div>}
      {canWrite && <Button onClick={save}>{t("common.save-changes")}</Button>}
    </>
  );
}

// GroupMembers edits a group repository's ordered member list. Changes apply
// on Save like the other settings panels.
function GroupMembers({ repo, setRepo }: { repo: Repository; setRepo: (r: Repository) => void }) {
  const { t } = useTranslation();
  const [repos, setRepos] = useState<Repository[]>([]);
  useEffect(() => {
    api.listRepositories().then(setRepos).catch(() => setRepos([]));
  }, []);

  const members = repo.config.group?.members ?? [];
  const setMembers = (m: string[]) =>
    setRepo({ ...repo, config: { ...repo.config, group: { members: m } } });
  const candidates = repos.filter(
    (r) => r.format === repo.format && r.type !== "group" && r.name !== repo.name && !members.includes(r.name),
  );

  return (
    <Card size="sm" className="mb-4">
      <CardContent>
      <h2 className="m-0 mb-4 text-base font-semibold">{t("repo.members")} <span className="text-xs font-normal text-muted-foreground">{t("repo.members-subtitle")}</span></h2>
      <MemberList members={members} onChange={setMembers}
        repoIndex={Object.fromEntries(repos.map((r) => [r.name, r.id]))}
        repoTypes={Object.fromEntries(repos.map((r) => [r.name, r.type]))} />
      <div className="flex min-w-0 items-center gap-2 mt-3 max-sm:flex-wrap items-stretch max-sm:flex-col">
        <Select value="" placeholder={t("repo.add-member-placeholder")}
          onChange={(v) => v && setMembers([...members, v])}
          options={candidates.map((r) => ({ value: r.name, label: `${r.name} (${r.type})` }))} />
      </div>
      </CardContent>
    </Card>
  );
}

// RepoPermissions lists, at a glance, which roles grant access to this
// repository (every role permission whose pattern matches the repo name),
// read-only. Admin-only tab. Assignment itself is managed on the Roles pages.
function RepoPermissions({ repoId }: { repoId: number }) {
  const { t } = useTranslation();
  const [perms, setPerms] = useState<RepoPermission[] | null>(null);
  const [tokens, setTokens] = useState<RepoToken[] | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    api.repositoryPermissions(repoId).then(setPerms).catch((e) => setError((e as Error).message));
    api.repositoryTokens(repoId).then(setTokens).catch((e) => setError((e as Error).message));
  }, [repoId]);

  return (
    <>
      <Card size="sm" className="mb-4">
        <CardContent>
        <h2 className="m-0 mb-4 text-base font-semibold">
          {t("common.roles")} <span className="text-xs font-normal text-muted-foreground">{t("repo.access-subtitle")}</span>
        </h2>
        {error && <Alert className="mb-4">{error}</Alert>}
        {!perms ? <div className="text-sm text-muted-foreground">{t("common.loading")}</div> : perms.length === 0 ? (
          <p className="m-0 text-sm text-muted-foreground">{t("repo.no-access-role")}</p>
        ) : (
          <TableWrap>
          <Table>
            <TableHeader>
              <TableRow><TableHead>{t("common.role")}</TableHead><TableHead>{t("repo.matched-pattern")}</TableHead><TableHead>{t("common.actions")}</TableHead><TableHead>{t("common.users")}</TableHead></TableRow>
            </TableHeader>
            <TableBody>
              {perms.map((p, i) => (
                <TableRow key={`${p.role_id}-${i}`}>
                  <TableCell><Link to="/access/roles/$id" params={{ id: String(p.role_id) }}>{p.role}</Link></TableCell>
                  <TableCell className="font-mono text-xs">{p.repo_pattern}</TableCell>
                  <TableCell>
                    <div className="flex min-w-0 flex-wrap items-center gap-1.5">
                      {p.actions.map((a) => <Badge key={a}>{a}</Badge>)}
                    </div>
                  </TableCell>
                  <TableCell>{p.user_count}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          </TableWrap>
        )}
        </CardContent>
      </Card>

      <Card size="sm" className="mb-4">
        <CardContent>
        <h2 className="m-0 mb-4 text-base font-semibold">
          {t("token.title")} <span className="text-xs font-normal text-muted-foreground">{t("repo.tokens-subtitle")}</span>
        </h2>
        {!tokens ? <div className="text-sm text-muted-foreground">{t("common.loading")}</div> : tokens.length === 0 ? (
          <p className="m-0 text-sm text-muted-foreground">{t("repo.no-access-token")}</p>
        ) : (
          <TableWrap>
          <Table>
            <TableHeader>
              <TableRow><TableHead>{t("common.token")}</TableHead><TableHead>{t("common.owner")}</TableHead><TableHead>{t("common.scope")}</TableHead><TableHead>{t("common.actions")}</TableHead><TableHead>{t("common.expires")}</TableHead></TableRow>
            </TableHeader>
            <TableBody>
              {tokens.map((tok) => (
                <TableRow key={tok.token_id}>
                  <TableCell>{tok.name}</TableCell>
                  <TableCell>{tok.owner || <span className="text-muted-foreground">{t("common.unknown")}</span>}</TableCell>
                  <TableCell className="font-mono text-xs">
                    {tok.unscoped
                      ? <span className="text-muted-foreground" title="Unscoped token: inherits the owner's role access to every repository.">{t("token.unscoped")}</span>
                      : tok.repo_pattern}
                  </TableCell>
                  <TableCell>
                    <div className="flex min-w-0 flex-wrap items-center gap-1.5">
                      {tok.unscoped
                        ? <span className="text-muted-foreground">{t("token.per-owner-roles")}</span>
                        : tok.actions.map((a) => <Badge key={a}>{a}</Badge>)}
                    </div>
                  </TableCell>
                  <TableCell className="text-muted-foreground">{tok.expires_at ? new Date(tok.expires_at).toLocaleDateString() : t("common.never")}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          </TableWrap>
        )}
        </CardContent>
      </Card>
    </>
  );
}

function Artifacts({ repoId, canDelete }: { repoId: number; canDelete: boolean }) {
  const { t } = useTranslation();
  const [data, setData] = useState<ArtifactList | null>(null);
  const [prefix, setPrefix] = useState("");
  const [error, setError] = useState("");
  const [deleting, setDeleting] = useState<Artifact | null>(null);
  const [scanningPath, setScanningPath] = useState("");

  const load = (p = prefix) =>
    api.listArtifacts(repoId, p).then(setData).catch((e) => setError(e.message));
  useEffect(() => { load(""); /* eslint-disable-next-line */ }, [repoId]);

  const del = async (a: Artifact) => {
    setError("");
    try {
      await api.deleteArtifact(repoId, a.path);
      setDeleting(null);
      load();
    } catch (e) {
      setError((e as Error).message);
      setDeleting(null);
    }
  };

  const scan = async (a: Artifact) => {
    setError("");
    setScanningPath(a.path);
    try {
      await api.scanArtifact(repoId, a.path);
      await load();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setScanningPath("");
    }
  };

  return (
    <Card size="sm" className="mb-4">
      <CardContent>
      <div className="mb-4 flex items-start justify-between gap-3 max-sm:flex-col max-sm:items-stretch">
        <h2 className="m-0 text-base font-semibold">{t("common.artifacts")}</h2>
        {data && <span className="text-sm text-muted-foreground">{data.count} items · {humanSize(data.total_size)}</span>}
      </div>
      {data && <ArtifactScanSummary artifacts={data.artifacts} />}
      <form className="mb-4 flex items-center gap-2 max-sm:flex-col max-sm:items-stretch" onSubmit={(e) => { e.preventDefault(); load(); }}>
        <Input placeholder="Filter by path prefix (e.g. com/acme or @scope/pkg)"
          value={prefix} onChange={(e) => setPrefix(e.target.value)} />
        <Button variant="outline" type="submit">{t("common.filter")}</Button>
      </form>
      {error && <Alert className="mb-4">{error}</Alert>}
      <TableWrap>
      <Table>
        <TableHeader>
          <TableRow><TableHead>{t("common.path")}</TableHead><TableHead>{t("common.version")}</TableHead><TableHead>{t("common.vuln")}</TableHead><TableHead>Artifact scan</TableHead><TableHead>{t("common.license")}</TableHead><TableHead>{t("common.size")}</TableHead><TableHead>{t("common.type")}</TableHead><TableHead>{t("common.last-accessed")}</TableHead>{canDelete && <TableHead></TableHead>}</TableRow>
        </TableHeader>
        <TableBody>
          {data?.artifacts.map((a) => (
            <TableRow key={a.path}>
              <TableCell className="break-all font-mono text-xs">{a.path}</TableCell>
              <TableCell>{a.version || "—"}</TableCell>
              <TableCell><SeverityBar severity={a.max_severity} counts={a.vuln_counts} source={a.vuln_source} scannedAt={a.vuln_scanned_at} /></TableCell>
              <TableCell><ArtifactScanBadge artifact={a} /></TableCell>
              <TableCell>
                {a.licenses && a.licenses.length > 0 ? (
                  <div className="flex min-w-0 flex-wrap items-center gap-1.5">
                    {a.licenses.map((licenseId) => <Badge key={licenseId} variant="outline">{licenseId}</Badge>)}
                  </div>
                ) : (
                  <span className="text-muted-foreground">—</span>
                )}
              </TableCell>
              <TableCell className="text-muted-foreground">{humanSize(a.size)}</TableCell>
              <TableCell className="text-muted-foreground">{a.content_type}</TableCell>
              <TableCell className="text-muted-foreground">{a.last_accessed_at?.slice(0, 19).replace("T", " ")}</TableCell>
              {canDelete && (
                <TableCell className="text-right">
                  <div className="flex justify-end gap-2">
                    <Button variant="outline" onClick={() => scan(a)} disabled={scanningPath === a.path}>
                      {a.artifact_scan_status ? "Rescan" : "Scan"}
                    </Button>
                    <Button variant="outline" onClick={() => setDeleting(a)}>{t("common.delete")}</Button>
                  </div>
                </TableCell>
              )}
            </TableRow>
          ))}
          {data && data.artifacts.length === 0 && (
            <TableRow><TableCell colSpan={canDelete ? 9 : 8} className="text-muted-foreground">{t("repo.no-cached-artifacts")}</TableCell></TableRow>
          )}
        </TableBody>
      </Table>
      </TableWrap>
      <ConfirmModal
        open={deleting !== null}
        title="Delete artifact"
        message={deleting
          ? `${deleting.path} will be removed from this repository. A proxy can re-cache it on the next request; a hosted upload cannot be recovered.`
          : undefined}
        confirmLabel={t("common.delete")}
        danger
        onConfirm={() => deleting && del(deleting)}
        onCancel={() => setDeleting(null)}
      />
      </CardContent>
    </Card>
  );
}

function ArtifactScanSummary({ artifacts }: { artifacts: Artifact[] }) {
  const counts = artifacts.reduce((acc, artifact) => {
    const status = artifact.artifact_scan_status || "unscanned";
    acc.total += 1;
    acc[status] = (acc[status] || 0) + 1;
    const findingCount = artifact.artifact_scan_finding_count ?? 0;
    if (status === "completed" && findingCount > 0) acc.findings += 1;
    return acc;
  }, { total: 0, queued: 0, running: 0, completed: 0, failed: 0, dead: 0, unscanned: 0, findings: 0 } as Record<string, number>);

  const items = [
    { label: "queued", value: counts.queued, variant: "outline" as const },
    { label: "running", value: counts.running, variant: "warning" as const },
    { label: "completed", value: counts.completed, variant: "success" as const },
    { label: "findings", value: counts.findings, variant: counts.findings > 0 ? "destructive" as const : "outline" as const },
    { label: "failed", value: (counts.failed || 0) + (counts.dead || 0), variant: "destructive" as const },
    { label: "unscanned", value: counts.unscanned, variant: "outline" as const },
  ];

  return (
    <div className="mb-4 flex min-w-0 flex-wrap items-center gap-2 rounded-[var(--radius)] border border-border bg-muted/30 px-3 py-2">
      <span className="mr-1 text-sm font-medium">Artifact scan</span>
      {items.map((item) => (
        <Badge key={item.label} variant={item.variant}>{item.label} {item.value}</Badge>
      ))}
    </div>
  );
}

function ArtifactScanBadge({ artifact }: { artifact: Artifact }) {
  const status = artifact.artifact_scan_status;
  if (!status) return <span className="text-muted-foreground">—</span>;
  const severity = artifact.artifact_scan_max_severity || "unknown";
  const count = artifact.artifact_scan_finding_count ?? 0;
  const title = [
    artifact.artifact_scan_scanner || "scanner",
    artifact.artifact_scan_scanned_at ? artifact.artifact_scan_scanned_at.slice(0, 19).replace("T", " ") : "",
  ].filter(Boolean).join(" · ");
  if (status !== "completed") {
    return <Badge variant={status === "failed" ? "destructive" : "outline"} title={title}>{status}</Badge>;
  }
  if (count === 0 || severity === "none" || severity === "unknown") {
    return <Badge variant="success" title={title}>clean</Badge>;
  }
  const variant = severity === "critical" || severity === "high" ? "destructive" : "warning";
  return <Badge variant={variant} title={title}>{severity} ×{count}</Badge>;
}

const AUDIT_EVENTS = ["", "download", "upload", "delete", "ttl.expire", "repo.create", "repo.update", "repo.delete",
  "approval.request", "approval.approve", "approval.reject"];
const AUDIT_PAGE_SIZE = 50;

function AuditLogs({ repoId }: { repoId: number }) {
  const { t } = useTranslation();
  const [data, setData] = useState<AuditLogList | null>(null);
  const [event, setEvent] = useState("");
  const [offset, setOffset] = useState(0);
  const [error, setError] = useState("");

  useEffect(() => {
    api.listAuditLogs(repoId, event, AUDIT_PAGE_SIZE, offset)
      .then(setData).catch((e) => setError(e.message));
  }, [repoId, event, offset]);

  const refresh = () =>
    api.listAuditLogs(repoId, event, AUDIT_PAGE_SIZE, offset)
      .then(setData).catch((e) => setError(e.message));

  return (
    <Card size="sm" className="mb-4">
      <CardContent>
      <div className="mb-4 flex items-start justify-between gap-3 max-sm:flex-col max-sm:items-stretch">
        <h2 className="m-0 text-base font-semibold">{t("repo.audit-log")}</h2>
        {data && <span className="text-sm text-muted-foreground">{data.count} events</span>}
      </div>
      <div className="flex min-w-0 items-center gap-2 mb-4 max-sm:flex-wrap items-stretch max-sm:flex-col">
        <Select value={event} onChange={(v) => { setEvent(v); setOffset(0); }}
          options={AUDIT_EVENTS.map((ev) => ({ value: ev, label: ev || "all events" }))} />
        <Button variant="outline" type="button" onClick={refresh}>{t("common.refresh")}</Button>
      </div>
      {error && <Alert className="mb-4">{error}</Alert>}
      <TableWrap>
      <Table>
        <TableHeader>
          <TableRow><TableHead>{t("common.time")}</TableHead><TableHead>{t("common.event")}</TableHead><TableHead>{t("common.path")}</TableHead><TableHead>{t("common.user")}</TableHead><TableHead>{t("common.status")}</TableHead><TableHead>{t("common.client-ip")}</TableHead></TableRow>
        </TableHeader>
        <TableBody>
          {data?.logs.map((l) => (
            <TableRow key={l.id}>
              <TableCell className="text-muted-foreground">{l.created_at?.slice(0, 19).replace("T", " ")}</TableCell>
              <TableCell><Badge>{l.event}</Badge></TableCell>
              <TableCell className="break-all font-mono text-xs">{l.path || "-"}</TableCell>
              <TableCell>{l.username || <span className="text-muted-foreground">{t("common.anonymous")}</span>}</TableCell>
              <TableCell className={l.status >= 400 ? "text-destructive" : "text-muted-foreground"}>{l.status}</TableCell>
              <TableCell className="text-muted-foreground">{l.client_ip}</TableCell>
            </TableRow>
          ))}
          {data && data.logs.length === 0 && (
            <TableRow><TableCell colSpan={6} className="text-muted-foreground">{t("repo.no-audit-events")}</TableCell></TableRow>
          )}
        </TableBody>
      </Table>
      </TableWrap>
      {data && data.count > AUDIT_PAGE_SIZE && (
        <div className="flex min-w-0 items-center gap-2 mt-3 max-sm:flex-wrap max-sm:flex-col max-sm:items-stretch">
          <Button variant="outline" type="button" disabled={offset === 0}
            onClick={() => setOffset(Math.max(0, offset - AUDIT_PAGE_SIZE))}>{t("common.newer")}</Button>
          <Button variant="outline" type="button" disabled={offset + AUDIT_PAGE_SIZE >= data.count}
            onClick={() => setOffset(offset + AUDIT_PAGE_SIZE)}>{t("common.older")}</Button>
          <span className="text-sm text-muted-foreground">{offset + 1}–{Math.min(offset + AUDIT_PAGE_SIZE, data.count)} of {data.count}</span>
        </div>
      )}
      </CardContent>
    </Card>
  );
}
