import { useEffect, useState } from "react";
import { createFileRoute, Link, Navigate, useNavigate, useParams } from "@tanstack/react-router";
import { api, Artifact, ArtifactList, AuditLogList, humanSize, Me, RepoPermission, RepoToken, repoEndpoint, Repository } from "../../../api";
import { useAuth } from "../../../authContext";
import { UpstreamStatus } from "../../../components/upstream-status";
import { ConfirmModal } from "../../../components/confirm-modal";
import { Alert } from "@/components/app-ui/alert";
import { Inline, PageHeader, Panel, PanelBody } from "@/components/app-ui/page";
import { Select } from "@/components/app-ui/select";
import { ActionBadge } from "@/components/app-ui/action-badge";
import { EventBadge } from "@/components/app-ui/event-badge";
import { FormatBadge, RepoTypeBadge } from "@/components/app-ui/repo-type-badge";
import { StateBadge } from "@/components/app-ui/status-badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  TableWrap,
} from "@/components/app-ui/table";
import { Toggle } from "../../../components/toggle";
import { MemberList } from "../new";
import { ApprovalList, SeverityBar, VersionDenies } from "../../approvals";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/repositories/$id/")({
  component: RepositoryDetailRoute,
});

function RepositoryDetailRoute() {
  const { me } = useAuth();
  return <RepositoryDetail me={me} />;
}

export function RepositoryDetail({ me }: { me: Me }) {
  const { id, tab: routeTab } = useParams({ strict: false }) as { id?: string; tab?: string };
  const tab = routeTab ?? "artifacts";
  const [repo, setRepo] = useState<Repository | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    api.getRepository(Number(id)).then(setRepo).catch((e) => setError(e.message));
  }, [id]);

  if (!repo) return error ? <Alert>{error}</Alert> : <div className="text-sm text-muted-foreground">Loading…</div>;

  // Tabs follow Nexus-style privileges: every authenticated reader can browse
  // Artifacts; Approvals needs the approve action; Permissions, Audit and
  // Settings are for admins and auditors (auditors see them read-only). Direct
  // URL access to a hidden tab redirects to Artifacts.
  const gated = repo.type === "proxy" && Boolean(repo.config.approval?.enabled);
  const canApprove = me.admin || me.approver;
  const canAdminView = me.admin || me.auditor;
  const tabs = [
    { key: "artifacts", label: "Artifacts" },
    ...(repo.type === "proxy" && canApprove ? [{ key: "approvals", label: "Approvals" }] : []),
    ...(canAdminView ? [{ key: "permissions", label: "Permissions" }, { key: "audit", label: "Audit" }, { key: "settings", label: "Settings" }] : []),
  ];

  if (!tabs.some((t) => t.key === tab)) {
    return <Navigate to="/repositories/$id/$tab" params={{ id: String(id), tab: "artifacts" }} replace />;
  }

  const endpoint = repoEndpoint(repo.format, repo.name);

  return (
    <>
      <PageHeader
        title={
          <Inline className="flex-wrap gap-2">
            <span className="min-w-0 truncate">{repo.name}</span>
            <RepoTypeBadge type={repo.type} />
            <FormatBadge format={repo.format} />
          </Inline>
        }
      />

      <Panel>
        <PanelBody>
        <h2 className="m-0 mb-4 text-base font-semibold">Client endpoint (forklift) <span className="text-xs font-normal text-muted-foreground">· read-only</span></h2>
        <Inline className="items-stretch max-sm:flex-col">
          <code className="flex-1 cursor-text select-all overflow-x-auto whitespace-nowrap rounded-[var(--radius)] border border-dashed border-border bg-input px-2.5 py-2 font-mono text-[13px] text-muted-foreground" title="Generated by forklift (read-only)">{endpoint.url}</code>
          <Button variant="outline" type="button"
            onClick={() => navigator.clipboard?.writeText(endpoint.url)}>Copy</Button>
        </Inline>
        {endpoint.hint && <p className="mt-2 text-sm text-muted-foreground">Configure in: {endpoint.hint}</p>}
        </PanelBody>
      </Panel>

      <nav className="mb-[18px] flex gap-1 border-b border-border max-[760px]:overflow-x-auto max-[760px]:pb-px">
        {tabs.map((t) => (
          <Link key={t.key} className={cn("mb-[-1px] rounded-t-[var(--radius)] border border-transparent border-b-0 px-3.5 py-[9px] text-sm text-muted-foreground hover:bg-muted hover:text-foreground hover:no-underline max-[760px]:whitespace-nowrap", tab === t.key && "border-border border-b-card bg-card text-primary")}
            to="/repositories/$id/$tab" params={{ id: String(id), tab: t.key }}>{t.label}</Link>
        ))}
      </nav>

      {tab === "artifacts" && <Artifacts repoId={repo.id} canDelete={!!me.admin} />}
      {tab === "permissions" && <RepoPermissions repoId={repo.id} />}
      {tab === "audit" && <AuditLogs repoId={repo.id} />}
      {tab === "approvals" && repo.type === "proxy" && (
        <>
          {gated && <ApprovalList repo={repo.name} showRepo={false} repoNames={[repo.name]} />}
          <VersionDenies repo={repo.name} showRepo={false} repoNames={[repo.name]} />
        </>
      )}
      {tab === "settings" && <Settings repo={repo} setRepo={setRepo} canWrite={!!me.admin} />}
    </>
  );
}

function Settings({ repo, setRepo, canWrite }: { repo: Repository; setRepo: (r: Repository) => void; canWrite: boolean }) {
  const navigate = useNavigate();
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [confirmPurge, setConfirmPurge] = useState(false);
  const [purged, setPurged] = useState<number | null>(null);

  const purge = async () => {
    setError("");
    setPurged(null);
    try {
      const { deleted } = await api.purgeArtifacts(repo.id);
      setConfirmPurge(false);
      setPurged(deleted);
    } catch (e) {
      setError((e as Error).message);
      setConfirmPurge(false);
    }
  };

  const save = async () => {
    setError("");
    setSaved(false);
    try {
      await api.updateRepository(repo.id, { upstream_url: repo.upstream_url, config: repo.config });
      setSaved(true);
    } catch (e) {
      setError((e as Error).message);
    }
  };

  const del = async () => {
    await api.deleteRepository(repo.id);
    navigate({ to: "/repositories" });
  };

  const cache = repo.config.cache;
  const age = repo.config.age_policy;
  // Older repos may predate the approval config section.
  const approval = repo.config.approval ?? { enabled: false, mode: "enforce", auto_approve: [] };
  const vuln = repo.config.vuln ?? { enabled: false, action: "audit", threshold: "high", ignore: [] };

  return (
    <>
      {!canWrite && (
        <p className="mt-0 text-sm text-muted-foreground">
          Read-only view. You can review the configuration but not change it.
        </p>
      )}
      <ConfirmModal
        open={confirmDelete}
        title={`Delete repository "${repo.name}"?`}
        message="This removes the repository and its cached/hosted artifacts. This cannot be undone."
        confirmLabel="Delete"
        danger
        onConfirm={del}
        onCancel={() => setConfirmDelete(false)}
      />

      {/* For an auditor (canWrite=false) the whole settings form is disabled via
          fieldset[disabled], which blocks every control (mouse and keyboard);
          they can read the configuration but not change it. */}
      <fieldset className="m-0 min-w-0 border-0 p-0 disabled:opacity-65" disabled={!canWrite}>
      <Panel>
        <PanelBody>
        <h2 className="m-0 mb-3 text-base font-semibold">State</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          {repo.disabled
            ? "This repository is offline: uploads and downloads are refused (503). Its config and artifacts are kept."
            : "This repository is online and serving the package protocols."}
        </p>
        {canWrite ? (
          <Toggle
            checked={!repo.disabled}
            label={repo.disabled ? "Offline" : "Online"}
            onChange={(online) => {
              setError("");
              api.setRepositoryDisabled(repo.id, !online).then(setRepo).catch((e) => setError((e as Error).message));
            }}
          />
        ) : (
          <StateBadge state={repo.disabled ? "offline" : "online"}>{repo.disabled ? "Offline" : "Online"}</StateBadge>
        )}
        </PanelBody>
      </Panel>

      {(repo.type === "proxy" || repo.type === "group") && (
        <h2 className="mt-6 mb-3 border-b border-border pb-[7px] text-xs font-semibold text-muted-foreground uppercase tracking-normal">Repository</h2>
      )}

      {repo.type === "proxy" && (
        <Panel>
          <PanelBody>
          <div className="mb-4 flex items-start justify-between gap-3 max-sm:flex-col max-sm:items-stretch">
            <h2 className="m-0 text-base font-semibold">Upstream</h2>
            <UpstreamStatus repoId={repo.id} withButton />
          </div>
          <Input value={repo.upstream_url}
            onChange={(e) => setRepo({ ...repo, upstream_url: e.target.value })} />
          </PanelBody>
        </Panel>
      )}

      {repo.type === "group" && <GroupMembers repo={repo} setRepo={setRepo} />}

      {repo.type === "proxy" && (
        <Panel>
          <PanelBody>
          <h2 className="m-0 mb-4 text-base font-semibold">Cache</h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={cache.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, enabled: !!checked } } })} />
            <span>Enable caching</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-3">
            <Field><FieldLabel>Metadata TTL</FieldLabel>
              <Input value={cache.metadata_ttl}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, metadata_ttl: e.target.value } } })} /></Field>
            <Field><FieldLabel>Negative TTL</FieldLabel>
              <Input value={cache.negative_ttl}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, negative_ttl: e.target.value } } })} /></Field>
            <Field><FieldLabel>Max size (bytes, 0 = unlimited)</FieldLabel>
              <Input type="number" value={cache.max_size_bytes}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, max_size_bytes: Number(e.target.value) } } })} /></Field>
          </FieldGroup>
          </PanelBody>
        </Panel>
      )}

      {repo.type === "proxy" && (
        <h2 className="mt-6 mb-3 border-b border-border pb-[7px] text-xs font-semibold text-muted-foreground uppercase tracking-normal">Security <span className="font-normal normal-case">· supply-chain policies</span></h2>
      )}

      {repo.type === "proxy" && (
        <Panel>
          <PanelBody>
          <h2 className="m-0 mb-4 text-base font-semibold">Age policy</h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={age.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, enabled: !!checked } } })} />
            <span>Enable supply-chain cooldown</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-2">
            <Field><FieldLabel>Min age (e.g. 3d)</FieldLabel>
              <Input value={age.min_age}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, min_age: e.target.value } } })} /></Field>
            <Field><FieldLabel>Action</FieldLabel>
              <Select value={age.action}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, action: v } } })}
                options={[
                  { value: "block", label: "block" },
                  { value: "warn", label: "warn" },
                ]} /></Field>
          </FieldGroup>
          </PanelBody>
        </Panel>
      )}

      {repo.type === "proxy" && (
        <Panel>
          <PanelBody>
          <h2 className="m-0 mb-4 text-base font-semibold">Package approval <span className="text-xs font-normal text-muted-foreground">· quarantine</span></h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={approval.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, approval: { ...approval, enabled: !!checked } } })} />
            <span>Require approval before serving a package</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-2">
            <Field><FieldLabel>Mode</FieldLabel>
              <Select value={approval.mode || "enforce"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, approval: { ...approval, mode: v } } })}
                options={[
                  { value: "enforce", label: "enforce (block unapproved)" },
                  { value: "audit", label: "audit (serve, log only)" },
                ]} /></Field>
            <Field><FieldLabel>Auto-approve patterns (one per line)</FieldLabel>
              <Textarea rows={3}
                value={(approval.auto_approve ?? []).join("\n")}
                placeholder={"@company/*"}
                onChange={(e) => setRepo({
                  ...repo,
                  config: {
                    ...repo.config,
                    approval: { ...approval, auto_approve: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
                  },
                })} /></Field>
          </FieldGroup>
          <p className="mb-0 mt-4 text-sm text-muted-foreground">Approval admits whole packages; version freshness is still gated by the age policy.</p>
          </PanelBody>
        </Panel>
      )}

      {repo.type === "proxy" && (
        <Panel>
          <PanelBody>
          <h2 className="m-0 mb-4 text-base font-semibold">Vulnerability policy <span className="text-xs font-normal text-muted-foreground">· OSV scan</span></h2>
          <label className="mb-4 flex items-center gap-2 text-sm">
            <Checkbox checked={vuln.enabled}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, enabled: !!checked } } })} />
            <span>Gate packages by known vulnerabilities</span>
          </label>
          <FieldGroup className="grid gap-4 md:grid-cols-2">
            <Field><FieldLabel>Threshold</FieldLabel>
              <Select value={vuln.threshold || "high"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, threshold: v } } })}
                options={[
                  { value: "critical", label: "critical" },
                  { value: "high", label: "high" },
                  { value: "medium", label: "medium" },
                  { value: "low", label: "low" },
                ]} /></Field>
            <Field><FieldLabel>Action</FieldLabel>
              <Select value={vuln.action || "audit"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, action: v } } })}
                options={[
                  { value: "block", label: "block (refuse to serve)" },
                  { value: "warn", label: "warn (serve, log)" },
                  { value: "audit", label: "audit (serve, log)" },
                ]} /></Field>
          </FieldGroup>
          <Field className="mt-4">
          <FieldLabel>Ignore advisories (CVE/GHSA/OSV, one per line)</FieldLabel>
          <Textarea rows={3}
            value={(vuln.ignore ?? []).join("\n")}
            placeholder={"CVE-2026-1234"}
            onChange={(e) => setRepo({
              ...repo,
              config: {
                ...repo.config,
                vuln: { ...vuln, ignore: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
              },
            })} />
          </Field>
          <label className="mt-3 flex items-center gap-2 text-sm">
            <Checkbox checked={!!vuln.block_unscanned}
              onCheckedChange={(checked) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, block_unscanned: !!checked } } })} />
            <span>Block versions not yet scanned (block action only)</span>
          </label>
          <p className="mb-0 mt-4 text-sm text-muted-foreground">Coordinate match against OSV (direct dependency only); transitive deps and artifact integrity are out of scope. Newly disclosed advisories surface on the next re-scan.</p>
          </PanelBody>
        </Panel>
      )}

      {repo.type !== "group" && (
        <Panel>
          <PanelBody>
          <h2 className="m-0 mb-4 text-base font-semibold">Artifact Retention <span className="text-xs font-normal text-muted-foreground">· idle auto-delete</span></h2>
          <Field>
            <FieldLabel>Idle TTL (e.g. 7d, 2w, 0 = keep forever)</FieldLabel>
              <Input value={repo.config.retention?.idle_ttl ?? ""}
                placeholder="0"
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, retention: { idle_ttl: e.target.value } } })} />
          </Field>
          <p className="mb-0 mt-4 text-sm text-muted-foreground">Artifacts not served for this long are deleted automatically; each removal is recorded in the audit log. Based on last-served time.</p>
          </PanelBody>
        </Panel>
      )}

      </fieldset>

      {error && <Alert className="mb-4">{error}</Alert>}
      {saved && <div className="mb-4 text-sm text-muted-foreground">Saved.</div>}
      {canWrite && repo.type !== "group" && <Button onClick={save}>Save changes</Button>}

      {canWrite && (
      <>
      <ConfirmModal
        open={confirmPurge}
        title={`Purge all artifacts in "${repo.name}"?`}
        message="This removes every cached or hosted artifact in the repository. The repository and its settings stay. A proxy will re-cache on demand; hosted uploads cannot be recovered."
        confirmLabel="Purge artifacts"
        danger
        onConfirm={purge}
        onCancel={() => setConfirmPurge(false)}
      />

      <Panel className="mt-4 border-destructive/70">
        <PanelBody>
        <h2 className="m-0 mb-3 text-base font-semibold text-destructive">Danger zone</h2>
        {repo.type !== "group" && (
          <>
            <p className="text-sm leading-relaxed text-muted-foreground">Purging removes all cached/hosted artifacts but keeps the repository and its settings. This cannot be undone.</p>
            {purged !== null && <div className="mb-3 text-sm text-muted-foreground">Purged {purged} {purged === 1 ? "artifact" : "artifacts"}.</div>}
            <Button variant="destructive" onClick={() => setConfirmPurge(true)}>Purge all artifacts</Button>
            <div className="my-4 border-t border-border" />
          </>
        )}
        <p className="text-sm leading-relaxed text-muted-foreground">Deleting a repository removes its cached/hosted artifacts. This cannot be undone.</p>
        <Button variant="destructive" onClick={() => setConfirmDelete(true)}>Delete repository</Button>
        </PanelBody>
      </Panel>
      </>
      )}
    </>
  );
}

// GroupMembers edits a group repository's ordered member list. Changes apply
// on Save like the other settings panels.
function GroupMembers({ repo, setRepo }: { repo: Repository; setRepo: (r: Repository) => void }) {
  const [repos, setRepos] = useState<Repository[]>([]);
  useEffect(() => {
    api.listRepositories().then(setRepos).catch(() => setRepos([]));
  }, []);

  const members = repo.config.group?.members ?? [];
  const setMembers = (m: string[]) =>
    setRepo({ ...repo, config: { ...repo.config, group: { members: m } } });
  const candidates = repos.filter(
    (r) => r.format === repo.format && r.type !== "group" && r.name !== repo.name && !members.includes(r.name),
  );

  return (
    <Panel>
      <PanelBody>
      <h2 className="m-0 mb-4 text-base font-semibold">Members <span className="text-xs font-normal text-muted-foreground">· lookup order, first hit wins</span></h2>
      <MemberList members={members} onChange={setMembers}
        repoIndex={Object.fromEntries(repos.map((r) => [r.name, r.id]))}
        repoTypes={Object.fromEntries(repos.map((r) => [r.name, r.type]))} />
      <Inline className="mt-3 items-stretch max-sm:flex-col">
        <Select value="" placeholder="add member…"
          onChange={(v) => v && setMembers([...members, v])}
          options={candidates.map((r) => ({ value: r.name, label: `${r.name} (${r.type})` }))} />
      </Inline>
      </PanelBody>
    </Panel>
  );
}

// RepoPermissions lists, at a glance, which roles grant access to this
// repository (every role permission whose pattern matches the repo name),
// read-only. Admin-only tab. Assignment itself is managed on the Roles pages.
function RepoPermissions({ repoId }: { repoId: number }) {
  const [perms, setPerms] = useState<RepoPermission[] | null>(null);
  const [tokens, setTokens] = useState<RepoToken[] | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    api.repositoryPermissions(repoId).then(setPerms).catch((e) => setError((e as Error).message));
    api.repositoryTokens(repoId).then(setTokens).catch((e) => setError((e as Error).message));
  }, [repoId]);

  return (
    <>
      <Panel>
        <PanelBody>
        <h2 className="m-0 mb-4 text-base font-semibold">
          Roles <span className="text-xs font-normal text-muted-foreground">· granting access to this repository</span>
        </h2>
        {error && <Alert className="mb-4">{error}</Alert>}
        {!perms ? <div className="text-sm text-muted-foreground">Loading…</div> : perms.length === 0 ? (
          <p className="m-0 text-sm text-muted-foreground">No role grants access to this repository. Add a permission on a role (Roles page) whose pattern matches this repository.</p>
        ) : (
          <TableWrap>
          <Table>
            <TableHeader>
              <TableRow><TableHead>Role</TableHead><TableHead>Matched pattern</TableHead><TableHead>Actions</TableHead><TableHead>Users</TableHead></TableRow>
            </TableHeader>
            <TableBody>
              {perms.map((p, i) => (
                <TableRow key={`${p.role_id}-${i}`}>
                  <TableCell><Link to="/roles/$id" params={{ id: String(p.role_id) }}>{p.role}</Link></TableCell>
                  <TableCell className="font-mono text-xs">{p.repo_pattern}</TableCell>
                  <TableCell>
                    <Inline className="flex-wrap gap-1.5">
                      {p.actions.map((a) => <ActionBadge key={a} action={a} />)}
                    </Inline>
                  </TableCell>
                  <TableCell>{p.user_count}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          </TableWrap>
        )}
        </PanelBody>
      </Panel>

      <Panel>
        <PanelBody>
        <h2 className="m-0 mb-4 text-base font-semibold">
          Access tokens <span className="text-xs font-normal text-muted-foreground">· reaching this repository</span>
        </h2>
        {!tokens ? <div className="text-sm text-muted-foreground">Loading…</div> : tokens.length === 0 ? (
          <p className="m-0 text-sm text-muted-foreground">No access token reaches this repository.</p>
        ) : (
          <TableWrap>
          <Table>
            <TableHeader>
              <TableRow><TableHead>Token</TableHead><TableHead>Owner</TableHead><TableHead>Scope</TableHead><TableHead>Actions</TableHead><TableHead>Expires</TableHead></TableRow>
            </TableHeader>
            <TableBody>
              {tokens.map((t) => (
                <TableRow key={t.token_id}>
                  <TableCell>{t.name}</TableCell>
                  <TableCell>{t.owner || <span className="text-muted-foreground">unknown</span>}</TableCell>
                  <TableCell className="font-mono text-xs">
                    {t.unscoped
                      ? <span className="text-muted-foreground" title="Unscoped token: inherits the owner's role access to every repository.">unscoped (inherits roles)</span>
                      : t.repo_pattern}
                  </TableCell>
                  <TableCell>
                    <Inline className="flex-wrap gap-1.5">
                      {t.unscoped
                        ? <span className="text-muted-foreground">per owner roles</span>
                        : t.actions.map((a) => <ActionBadge key={a} action={a} />)}
                    </Inline>
                  </TableCell>
                  <TableCell className="text-muted-foreground">{t.expires_at ? new Date(t.expires_at).toLocaleDateString() : "never"}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          </TableWrap>
        )}
        </PanelBody>
      </Panel>
    </>
  );
}

function Artifacts({ repoId, canDelete }: { repoId: number; canDelete: boolean }) {
  const [data, setData] = useState<ArtifactList | null>(null);
  const [prefix, setPrefix] = useState("");
  const [error, setError] = useState("");
  const [deleting, setDeleting] = useState<Artifact | null>(null);

  const load = (p = prefix) =>
    api.listArtifacts(repoId, p).then(setData).catch((e) => setError(e.message));
  useEffect(() => { load(""); /* eslint-disable-next-line */ }, [repoId]);

  const del = async (a: Artifact) => {
    setError("");
    try {
      await api.deleteArtifact(repoId, a.path);
      setDeleting(null);
      load();
    } catch (e) {
      setError((e as Error).message);
      setDeleting(null);
    }
  };

  return (
    <Panel>
      <PanelBody>
      <div className="mb-4 flex items-start justify-between gap-3 max-sm:flex-col max-sm:items-stretch">
        <h2 className="m-0 text-base font-semibold">Artifacts</h2>
        {data && <span className="text-sm text-muted-foreground">{data.count} items · {humanSize(data.total_size)}</span>}
      </div>
      <form className="mb-4 flex items-center gap-2 max-sm:flex-col max-sm:items-stretch" onSubmit={(e) => { e.preventDefault(); load(); }}>
        <Input placeholder="Filter by path prefix (e.g. com/acme or @scope/pkg)"
          value={prefix} onChange={(e) => setPrefix(e.target.value)} />
        <Button variant="outline" type="submit">Filter</Button>
      </form>
      {error && <Alert className="mb-4">{error}</Alert>}
      <TableWrap>
      <Table>
        <TableHeader>
          <TableRow><TableHead>Path</TableHead><TableHead>Version</TableHead><TableHead>Vuln</TableHead><TableHead>Size</TableHead><TableHead>Type</TableHead><TableHead>Last accessed</TableHead>{canDelete && <TableHead></TableHead>}</TableRow>
        </TableHeader>
        <TableBody>
          {data?.artifacts.map((a) => (
            <TableRow key={a.path}>
              <TableCell className="break-all font-mono text-xs">{a.path}</TableCell>
              <TableCell>{a.version || "—"}</TableCell>
              <TableCell><SeverityBar severity={a.max_severity} counts={a.vuln_counts} source={a.vuln_source} scannedAt={a.vuln_scanned_at} /></TableCell>
              <TableCell className="text-muted-foreground">{humanSize(a.size)}</TableCell>
              <TableCell className="text-muted-foreground">{a.content_type}</TableCell>
              <TableCell className="text-muted-foreground">{a.last_accessed_at?.slice(0, 19).replace("T", " ")}</TableCell>
              {canDelete && (
                <TableCell className="text-right">
                  <Button variant="outline" onClick={() => setDeleting(a)}>Delete</Button>
                </TableCell>
              )}
            </TableRow>
          ))}
          {data && data.artifacts.length === 0 && (
            <TableRow><TableCell colSpan={canDelete ? 7 : 6} className="text-muted-foreground">No cached artifacts yet. Pull through the endpoint above to populate the cache.</TableCell></TableRow>
          )}
        </TableBody>
      </Table>
      </TableWrap>
      <ConfirmModal
        open={deleting !== null}
        title="Delete artifact"
        message={deleting
          ? `${deleting.path} will be removed from this repository. A proxy can re-cache it on the next request; a hosted upload cannot be recovered.`
          : undefined}
        confirmLabel="Delete"
        danger
        onConfirm={() => deleting && del(deleting)}
        onCancel={() => setDeleting(null)}
      />
      </PanelBody>
    </Panel>
  );
}

const AUDIT_EVENTS = ["", "download", "upload", "delete", "ttl.expire", "repo.create", "repo.update", "repo.delete",
  "approval.request", "approval.approve", "approval.reject"];
const AUDIT_PAGE_SIZE = 50;

function AuditLogs({ repoId }: { repoId: number }) {
  const [data, setData] = useState<AuditLogList | null>(null);
  const [event, setEvent] = useState("");
  const [offset, setOffset] = useState(0);
  const [error, setError] = useState("");

  useEffect(() => {
    api.listAuditLogs(repoId, event, AUDIT_PAGE_SIZE, offset)
      .then(setData).catch((e) => setError(e.message));
  }, [repoId, event, offset]);

  const refresh = () =>
    api.listAuditLogs(repoId, event, AUDIT_PAGE_SIZE, offset)
      .then(setData).catch((e) => setError(e.message));

  return (
    <Panel>
      <PanelBody>
      <div className="mb-4 flex items-start justify-between gap-3 max-sm:flex-col max-sm:items-stretch">
        <h2 className="m-0 text-base font-semibold">Audit log</h2>
        {data && <span className="text-sm text-muted-foreground">{data.count} events</span>}
      </div>
      <Inline className="mb-4 items-stretch max-sm:flex-col">
        <Select value={event} onChange={(v) => { setEvent(v); setOffset(0); }}
          options={AUDIT_EVENTS.map((ev) => ({ value: ev, label: ev || "all events" }))} />
        <Button variant="outline" type="button" onClick={refresh}>Refresh</Button>
      </Inline>
      {error && <Alert className="mb-4">{error}</Alert>}
      <TableWrap>
      <Table>
        <TableHeader>
          <TableRow><TableHead>Time</TableHead><TableHead>Event</TableHead><TableHead>Path</TableHead><TableHead>User</TableHead><TableHead>Status</TableHead><TableHead>Client IP</TableHead></TableRow>
        </TableHeader>
        <TableBody>
          {data?.logs.map((l) => (
            <TableRow key={l.id}>
              <TableCell className="text-muted-foreground">{l.created_at?.slice(0, 19).replace("T", " ")}</TableCell>
              <TableCell><EventBadge event={l.event} /></TableCell>
              <TableCell className="break-all font-mono text-xs">{l.path || "-"}</TableCell>
              <TableCell>{l.username || <span className="text-muted-foreground">anonymous</span>}</TableCell>
              <TableCell className={l.status >= 400 ? "text-destructive" : "text-muted-foreground"}>{l.status}</TableCell>
              <TableCell className="text-muted-foreground">{l.client_ip}</TableCell>
            </TableRow>
          ))}
          {data && data.logs.length === 0 && (
            <TableRow><TableCell colSpan={6} className="text-muted-foreground">No audit events recorded yet.</TableCell></TableRow>
          )}
        </TableBody>
      </Table>
      </TableWrap>
      {data && data.count > AUDIT_PAGE_SIZE && (
        <Inline className="mt-3 max-sm:flex-col max-sm:items-stretch">
          <Button variant="outline" type="button" disabled={offset === 0}
            onClick={() => setOffset(Math.max(0, offset - AUDIT_PAGE_SIZE))}>Newer</Button>
          <Button variant="outline" type="button" disabled={offset + AUDIT_PAGE_SIZE >= data.count}
            onClick={() => setOffset(offset + AUDIT_PAGE_SIZE)}>Older</Button>
          <span className="text-sm text-muted-foreground">{offset + 1}–{Math.min(offset + AUDIT_PAGE_SIZE, data.count)} of {data.count}</span>
        </Inline>
      )}
      </PanelBody>
    </Panel>
  );
}
