{{- if and .Values.artifactScanning.enabled .Values.artifactScanning.worker.enabled .Values.artifactScanning.worker.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "forklift.fullname" . }}-scanner
  labels:
    {{- include "forklift.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "forklift.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scanner
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "forklift.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}
