/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as TokensNewRouteImport } from './routes/tokens.new'
import { Route as RolesNewRouteImport } from './routes/roles.new'
import { Route as RolesIdRouteImport } from './routes/roles.$id'
import { Route as RepositoriesNewRouteImport } from './routes/repositories.new'
import { Route as RepositoriesIdRouteImport } from './routes/repositories.$id'
import { Route as ApprovalsIdRouteImport } from './routes/approvals.$id'
import { Route as RepositoriesIdTabRouteImport } from './routes/repositories.$id.$tab'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)
const TokensNewRoute = TokensNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TokensRoute,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RolesRoute,
} as any)
const RolesIdRoute = RolesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RolesRoute,
} as any)
const RepositoriesNewRoute = RepositoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RepositoriesRoute,
} as any)
const RepositoriesIdRoute = RepositoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepositoriesRoute,
} as any)
const ApprovalsIdRoute = ApprovalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApprovalsRoute,
} as any)
const RepositoriesIdTabRoute = RepositoriesIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => RepositoriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/roles': typeof RolesRouteWithChildren
  '/tokens': typeof TokensRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/approvals/$id': typeof ApprovalsIdRoute
  '/repositories/$id': typeof RepositoriesIdRouteWithChildren
  '/repositories/new': typeof RepositoriesNewRoute
  '/roles/$id': typeof RolesIdRoute
  '/roles/new': typeof RolesNewRoute
  '/tokens/new': typeof TokensNewRoute
  '/users/$id': typeof UsersIdRoute
  '/users/new': typeof UsersNewRoute
  '/repositories/$id/$tab': typeof RepositoriesIdTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/roles': typeof RolesRouteWithChildren
  '/tokens': typeof TokensRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/approvals/$id': typeof ApprovalsIdRoute
  '/repositories/$id': typeof RepositoriesIdRouteWithChildren
  '/repositories/new': typeof RepositoriesNewRoute
  '/roles/$id': typeof RolesIdRoute
  '/roles/new': typeof RolesNewRoute
  '/tokens/new': typeof TokensNewRoute
  '/users/$id': typeof UsersIdRoute
  '/users/new': typeof UsersNewRoute
  '/repositories/$id/$tab': typeof RepositoriesIdTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/roles': typeof RolesRouteWithChildren
  '/tokens': typeof TokensRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/approvals/$id': typeof ApprovalsIdRoute
  '/repositories/$id': typeof RepositoriesIdRouteWithChildren
  '/repositories/new': typeof RepositoriesNewRoute
  '/roles/$id': typeof RolesIdRoute
  '/roles/new': typeof RolesNewRoute
  '/tokens/new': typeof TokensNewRoute
  '/users/$id': typeof UsersIdRoute
  '/users/new': typeof UsersNewRoute
  '/repositories/$id/$tab': typeof RepositoriesIdTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/repositories'
    | '/roles'
    | '/tokens'
    | '/users'
    | '/approvals/$id'
    | '/repositories/$id'
    | '/repositories/new'
    | '/roles/$id'
    | '/roles/new'
    | '/tokens/new'
    | '/users/$id'
    | '/users/new'
    | '/repositories/$id/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/repositories'
    | '/roles'
    | '/tokens'
    | '/users'
    | '/approvals/$id'
    | '/repositories/$id'
    | '/repositories/new'
    | '/roles/$id'
    | '/roles/new'
    | '/tokens/new'
    | '/users/$id'
    | '/users/new'
    | '/repositories/$id/$tab'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/repositories'
    | '/roles'
    | '/tokens'
    | '/users'
    | '/approvals/$id'
    | '/repositories/$id'
    | '/repositories/new'
    | '/roles/$id'
    | '/roles/new'
    | '/tokens/new'
    | '/users/$id'
    | '/users/new'
    | '/repositories/$id/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRouteWithChildren
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  RolesRoute: typeof RolesRouteWithChildren
  TokensRoute: typeof TokensRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/tokens/new': {
      id: '/tokens/new'
      path: '/new'
      fullPath: '/tokens/new'
      preLoaderRoute: typeof TokensNewRouteImport
      parentRoute: typeof TokensRoute
    }
    '/roles/new': {
      id: '/roles/new'
      path: '/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof RolesRoute
    }
    '/roles/$id': {
      id: '/roles/$id'
      path: '/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof RolesIdRouteImport
      parentRoute: typeof RolesRoute
    }
    '/repositories/new': {
      id: '/repositories/new'
      path: '/new'
      fullPath: '/repositories/new'
      preLoaderRoute: typeof RepositoriesNewRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/repositories/$id': {
      id: '/repositories/$id'
      path: '/$id'
      fullPath: '/repositories/$id'
      preLoaderRoute: typeof RepositoriesIdRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/approvals/$id': {
      id: '/approvals/$id'
      path: '/$id'
      fullPath: '/approvals/$id'
      preLoaderRoute: typeof ApprovalsIdRouteImport
      parentRoute: typeof ApprovalsRoute
    }
    '/repositories/$id/$tab': {
      id: '/repositories/$id/$tab'
      path: '/$tab'
      fullPath: '/repositories/$id/$tab'
      preLoaderRoute: typeof RepositoriesIdTabRouteImport
      parentRoute: typeof RepositoriesIdRoute
    }
  }
}

interface ApprovalsRouteChildren {
  ApprovalsIdRoute: typeof ApprovalsIdRoute
}

const ApprovalsRouteChildren: ApprovalsRouteChildren = {
  ApprovalsIdRoute: ApprovalsIdRoute,
}

const ApprovalsRouteWithChildren = ApprovalsRoute._addFileChildren(
  ApprovalsRouteChildren,
)

interface RepositoriesIdRouteChildren {
  RepositoriesIdTabRoute: typeof RepositoriesIdTabRoute
}

const RepositoriesIdRouteChildren: RepositoriesIdRouteChildren = {
  RepositoriesIdTabRoute: RepositoriesIdTabRoute,
}

const RepositoriesIdRouteWithChildren = RepositoriesIdRoute._addFileChildren(
  RepositoriesIdRouteChildren,
)

interface RepositoriesRouteChildren {
  RepositoriesIdRoute: typeof RepositoriesIdRouteWithChildren
  RepositoriesNewRoute: typeof RepositoriesNewRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesIdRoute: RepositoriesIdRouteWithChildren,
  RepositoriesNewRoute: RepositoriesNewRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

interface RolesRouteChildren {
  RolesIdRoute: typeof RolesIdRoute
  RolesNewRoute: typeof RolesNewRoute
}

const RolesRouteChildren: RolesRouteChildren = {
  RolesIdRoute: RolesIdRoute,
  RolesNewRoute: RolesNewRoute,
}

const RolesRouteWithChildren = RolesRoute._addFileChildren(RolesRouteChildren)

interface TokensRouteChildren {
  TokensNewRoute: typeof TokensNewRoute
}

const TokensRouteChildren: TokensRouteChildren = {
  TokensNewRoute: TokensNewRoute,
}

const TokensRouteWithChildren =
  TokensRoute._addFileChildren(TokensRouteChildren)

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRoute
  UsersNewRoute: typeof UsersNewRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRoute,
  UsersNewRoute: UsersNewRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRouteWithChildren,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  RolesRoute: RolesRouteWithChildren,
  TokensRoute: TokensRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
